language: python
sudo: false

matrix:
    include:
        - python: "2.7"
          env: VERSION_FILE=version_plone51.cfg

script:
    - pip install -U pip
    - pip install -r requirements.txt
    - ./bin/buildout -c "$VERSION_FILE" && echo "Buildout ran successfully"
    - ./bin/test && echo "Tests ran successfully"

notifications:
    email: false
